name: Rebuild README

on:
  push:
    branches: [ master ]
    tags-ignore: 
      - 'v*'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]
    tags-ignore: 
      - 'v*'
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    name : Build README

    runs-on: 'ubuntu-latest'
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: release
      
      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v1
      
      - name: Get dependencies for integration testing
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(pkgdir = ".", dependencies = TRUE), ".github/packages.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      
      - name: Install dependencies
        run: |
          remotes::install_cran("rmarkdown")
          remotes::install_local(".", dependencies = TRUE)
        shell: Rscript {0}
        
      - name: Cache installed R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/packages.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
        
      - name: Generate README
        run: |
          options(crayon.enabled = FALSE)
          rmarkdown::render("README.Rmd")
        shell: Rscript {0}
        
      - name: Upload README
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: 'Auto-generated README.md'
          add: 'README.md'
